# .goreleaser.yaml
version: 2

project_name: hddviz

builds:
  - id: hddviz
    dir: ./src
    main: .
    binary: hddviz
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: hddviz
    repository:
      owner: Toyakki
      name: homebrew-hddviz
      branch: main
      token: "{{ .ENV.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    commit_author:
      name: hddviz-bot
      email: bot@users.noreply.github.com

    homepage: "https://github.com/Toyakki/hddviz"
    description: "CLI tool to simplify HDD usage visualization"
    license: "GPL-3.0-only"

    binaries:
      - hddviz

    url:
      verified: "github.com/Toyakki/hddviz/releases/download/"