# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.1.5"

  on_macos do
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
    sha256 "2afc88c360377f741766da33f55086296cec3198ed5a385ecc73425f33df42aa"
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hddviz"]
    end
  end

  # No zap stanza required

end
