# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.1.4"

  on_macos do
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
    sha256 "4023a0b2faeaa8ce5d88314131c75c681c7b91d42c82c46ecf358448cfc1e9b9"
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
      sha256 "1991c517389e63b48864be0ceb25bb032d69aea57c143e81865b14c0d860fcc9"
    end
    on_arm do
      url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
      sha256 "6daaa9b62450f42e817aa39b4560017acd8445454f2bc1efd9a00ae97de09574"
    end
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hddviz"]
    end
  end

  # No zap stanza required

end
