# This file was generated by GoReleaser. DO NOT EDIT.
cask "hddviz" do
  version "0.1.3"

  on_macos do
    url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_darwin_all.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
    sha256 "71a2c3ffdecdbf70f337116f928a3b5344d41870c98b03809b924f1c6e49b408"
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
      sha256 "39356cf14f841a9ef06ad498d7b62797068f3bf13e81a87e36088478cd6e23d8"
    end
    on_arm do
      url "https://github.com/Toyakki/hddviz/releases/download/v#{version}/hddviz_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Toyakki/hddviz/"
      sha256 "d3cef904d54b3efc0fba6903ed0a77e277b1d937806f83db0e27cc1f459a7434"
    end
  end

  name "hddviz"
  desc "CLI tool to simplify HDD usage visualization"
  homepage "https://github.com/Toyakki/hddviz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hddviz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hddviz"]
    end
  end

  # No zap stanza required

end
