name: release

on:
  push:
    branches: ["main"]
    paths:
      - "VERSION"
    tags:
      - 'v*'
  # manual trigger for releases
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., v1.0.0)"
        required: true
        type: string
        default: "0.1.0"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          # Installs and runs a GoReleaser v2.x release
          version: "~> v2"
          # Remove the previous dist/ folder before new release.
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HDDVIZ_PAT }}
